import type { Metadata } from "next";
import { Geist, Geist_Mono, AR_One_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const oneSans = AR_One_Sans({
  variable: "--font-one-sans",
  subsets : ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${oneSans.variable} antialiased`}
      >
        <Navbar>
          
        </Navbar>
        <div className="flex items-center justify-center">
         {children}
        </div>
       
      </body>
    </html>
  );
}
